### ISSUE TITLE
Pack fails in github actions when building packaging windows release on UbuntuLatest runner

### ISSUE THREAD

**Issue by henry-js** [velopack/velopack#115]
I'm using nuke.build to run the vpk cli. When executing in a github action I'm getting the following error

```
[12:44:22 INF] Velopack CLI 0.0.462-gf8acc97 (prerelease), for distributing applications.
     [12:44:23 WRN] There is a newer version of vpk available. Run 'dotnet tool update -g vpk --version 0.0.474-gb9d73fc'
     [12:44:23 INF] Beginning to package Velopack release 0.0.1.
     [12:44:23 INF] Releases Directory: /home/runner/work/tasktitan/tasktitan/release/win-x64
     [12:44:23 INF] Starting: Pre-process steps
     [12:44:23 INF] Building new .AppDir
     [12:44:23 INF] Complete: Pre-process steps
     [12:44:23 INF] Starting: Building portable package
     [12:44:23 FTL] Command LinuxPackCommand had an exception.
     System.ArgumentException: Given stream is not a proper ELF file.
        at ELFSharp.ELF.ELFReader.Load(Stream stream, Boolean shouldOwnStream)
        at ELFSharp.ELF.ELFReader.Load(String fileName)
        at Velopack.Packaging.Unix.Commands.LinuxPackCommandRunner.GetMachineForBinary(String path) in ./Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs:line 109
        at Velopack.Packaging.Unix.Commands.LinuxPackCommandRunner.CreatePortablePackage(Action`1 progress, String packDir, String outputPath) in ./Velopack.Packaging.Unix/Commands/LinuxPackCommandRunner.cs:line [98](https://github.com/henry-js/tasktitan/actions/runs/9128413386/job/25100713752#step:4:104)
        at Velopack.Packaging.PackageBuilder`1.<>c__DisplayClass35_0.<<Run>b__4>d.MoveNext() in ./Velopack.Packaging/PackageBuilder.cs:line 125
     --- End of stack trace from previous location ---
        at Velopack.Vpk.Logging.BasicConsole.Progress.RunTask(String name, Func`2 fn) in ./Velopack.Vpk/Logging/BasicConsole.cs:line 58
        at Velopack.Packaging.PackageBuilder`1.<>c__DisplayClass35_0.<<Run>b__1>d.MoveNext() in ./Velopack.Packaging/PackageBuilder.cs:line 130
     --- End of stack trace from previous location ---
        at Velopack.Vpk.Logging.BasicConsole.ExecuteProgressAsync(Func`2 action) in ./Velopack.Vpk/Logging/BasicConsole.cs:line 24
        at Velopack.Packaging.PackageBuilder`1.Run(T options) in ./Velopack.Packaging/PackageBuilder.cs:line [107](https://github.com/henry-js/tasktitan/actions/runs/9128413386/job/25100713752#step:4:113)
        at Velopack.Vpk.ProgramCommandExtensions.<>c__DisplayClass3_0`2.<<Add>b__0>d.MoveNext() in ./Velopack.Vpk/Program.cs:line 206
  
     at Nuke.Common.Tooling.ProcessExtensions.AssertZeroExitCode(IProcess process) in /_/source/Nuke.Tooling/ProcessExtensions.cs:line 39
     at Nuke.Common.Tooling.ProcessTasks.DefaultExitHandler(ToolSettings toolSettings, IProcess process) in /_/source/Nuke.Tooling/ProcessTasks.cs:line 257
     at Nuke.Common.Tooling.ToolExecutor.<>c.<Execute>b__2_0(IProcess p) in /_/source/Nuke.Tooling/ToolExecutor.cs:line 63
     at Nuke.Common.Tooling.ToolExecutor.Execute(ArgumentStringHandler arguments, String workingDirectory, IReadOnlyDictionary`2 environmentVariables, Nullable`1 timeout, Nullable`1 logOutput, Nullable`1 logInvocation, Action`2 logger, Action`1 exitHandler) in /_/source/Nuke.Tooling/ToolExecutor.cs:line 63
     at Build.<get_Release>b__35_2() in /home/runner/work/tasktitan/tasktitan/build/Build.cs:line 157
     at Nuke.Common.Execution.BuildExecutor.<>c.<Execute>b__4_2(Action x) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line 119
     at System.Collections.Generic.List`1.ForEach(Action`1 action)
     at Nuke.Common.Execution.BuildExecutor.Execute(NukeBuild build, ExecutableTarget target, IReadOnlyCollection`1 previouslyExecutedTargets, Boolean failureMode) in /_/source/Nuke.Build/Execution/BuildExecutor.cs:line [119](https://github.com/henry-js/tasktitan/actions/runs/9128413386/job/25100713752#step:4:125)
```

Can I not build windows installers on Linux?

**Comment by caesay** [comment]
At the moment this is not supported, please see https://github.com/velopack/velopack/issues/18
