### ISSUE TITLE
Exception while trying to sign

### ISSUE THREAD

**Issue by leonidcan** [velopack/velopack#12]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Velopack.ProcessStartExtensions.AppendArgumentListSafe(ProcessStartInfo psi, IEnumerable`1 args, String& debug) in ./Velopack/Internal/ProcessExtensions.cs:line 18
   at Velopack.Packaging.Exe.InvokeProcess(String fileName, IEnumerable`1 args, String workingDirectory, CancellationToken ct) in ./Velopack.Packaging/Exe.cs:line 61
   at Velopack.Packaging.Windows.CodeSign.SignPEFileWithTemplate(String filePath, String signTemplate) in ./Velopack.Packaging.Windows/CodeSign.cs:line 103
   at Velopack.Packaging.Windows.Commands.WindowsPackCommandRunner.SignFilesImpl(WindowsSigningOptions options, String rootDir, Action`1 progress, String[] filePaths) in ./Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs:line 208
   at Velopack.Packaging.Windows.Commands.WindowsPackCommandRunner.CodeSign(Action`1 progress, String packDir) in ./Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs:line 29
   at Velopack.Packaging.PackageBuilder`1.<>c__DisplayClass28_0.<<Run>b__3>d.MoveNext() in ./Velopack.Packaging/PackageBuilder.cs:line 124
--- End of stack trace from previous location ---
   at Velopack.Packaging.Progress.RunTask(String name, Func`2 fn) in ./Velopack.Packaging/Progress.cs:line 71
   at Velopack.Packaging.PackageBuilder`1.<>c__DisplayClass28_0.<<Run>b__1>d.MoveNext() in ./Velopack.Packaging/PackageBuilder.cs:line 123
--- End of stack trace from previous location ---
   at Velopack.Packaging.Progress.ExecuteAsync(ILogger logger, Func`2 action) in ./Velopack.Packaging/Progress.cs:line 43
   at Velopack.Packaging.PackageBuilder`1.Run(T options) in ./Velopack.Packaging/PackageBuilder.cs:line 115
   at Velopack.Vpk.Compat.RunnerFactory.CreateAndExecuteAsync[T](String commandName, T options) in ./Velopack.Vpk/Compat/RunnerFactory.cs:line 26
```

Using signtool seems to work fine. For the setup however after downloading Windows gives warning and tries to block.

**Comment by caesay** [comment]
I don't actually have a code signing certificate for windows so I can't test this at the moment, can you show me what command you are trying to run? Also, what do you mean by "after downloading Windows gives warning and tries to block".

**Comment by leonidcan** [comment]
I use the same arguments as for signtool  (this works fine)
$signtool sign `
          /v `
          /fd SHA256 `
          /debug `
          /t http://timestamp.digicert.com `
          /n $personalCertificateName `
          .setup.exe

Windows usually blocks programs downloaded from unknown source (this could be just because I downloaded from development env and not from production). It shows a dialog that it blocked the app and offers to the user to allow it. I don't have a screenshot handy, if I see it again I will post.

**Comment by caesay** [comment]
You didn't share the args you were passing to Velopack (which was really what I was asking). Given your signtool arguments, you should be passing:

```cmd
vpk ... --signParams "/v  /fd SHA256  /debug  /t http://timestamp.digicert.com  /n $personalCertificateName"
```

And quite possibly, you might need to add some escaped quotes around $personalCertificateName if there are any spaces in it. 

Velopack doesn't just sign Setup.exe, but also the application files inside. Should you choose to do signing yourself without relying on Velopack, you should sign all your application binaries before calling `pack`, and then sign Setup.exe after the pack has completed. 

In regards to the Windows warning about untrusted software etc, obviously I can't help with that - these kinds of dialogs come from everywhere. Even Chrome has their own version of them, so in the worst case, the user might have to accept the browser disclaimer _and_ the windows one. 

You can build up trust for your binaries by distributing them from the same URL and always signing them with the same certificate. Once Windows/Microsoft & Google have seen your binaries a handful of times, this warning will go away.

**Comment by leonidcan** [comment]
Signing issue was indeed caused by spaces. Thanks. I think this can be closed.

**Comment by leonidcan** [comment]
Signing issue was indeed caused by spaces.
