### ISSUE TITLE
PlaceHolderNotFoundInAppHostException when packing on Windows

### ISSUE THREAD

**Issue by caesay** [velopack/velopack#121]
I need urgent help please.

I get the following exception when running vpk pack, it was running successfully all along, I don't know what changed now:

Command WindowsPackCommand had an exception.
Microsoft.NET.HostModel.AppHost.PlaceHolderNotFoundInAppHostException: Exception of type 'Microsoft.NET.HostModel.AppHost.PlaceHolderNotFoundInAppHostException' was thrown.
at Velopack.Packaging.Windows.SetupBundle.<>c__DisplayClass0_0.g__FindBundleHeader|0() in ./Velopack.Packaging.Windows/SetupBundle.cs:line 28
at Velopack.Utility.<>c__DisplayClass19_0.b__0() in ./Velopack/Internal/Utility.cs:line 197
at Velopack.Utility.Retry[T](Func1 block, Int32 retries, Int32 retryDelay, ILogger logger) in ./Velopack/Internal/Utility.cs:line 208 at Velopack.Utility.Retry(Action block, Int32 retries, Int32 retryDelay, ILogger logger) in ./Velopack/Internal/Utility.cs:line 196 at Velopack.Packaging.Windows.SetupBundle.IsBundle(String setupPath, Int64& bundleOffset, Int64& bundleLength) in ./Velopack.Packaging.Windows/SetupBundle.cs:line 36 at Velopack.Packaging.Windows.SetupBundle.CreatePackageBundle(String setupPath, String packagePath) in ./Velopack.Packaging.Windows/SetupBundle.cs:line 84 at Velopack.Packaging.Windows.Commands.WindowsPackCommandRunner.CreateSetupPackage(Action1 progress, String releasePkg, String packDir, String targetSetupExe) in ./Velopack.Packaging.Windows/Commands/WindowsPackCommandRunner.cs:line 148
at Velopack.Packaging.PackageBuilder1.<>c__DisplayClass36_1.<<Run>b__6>d.MoveNext() in ./Velopack.Packaging/PackageBuilder.cs:line 143 --- End of stack trace from previous location --- at Velopack.Vpk.Logging.BasicConsole.Progress.RunTask(String name, Func2 fn) in ./Velopack.Vpk/Logging/BasicConsole.cs:line 53
at Velopack.Packaging.PackageBuilder1.<>c__DisplayClass36_0.<<Run>b__1>d.MoveNext() in ./Velopack.Packaging/PackageBuilder.cs:line 155 --- End of stack trace from previous location --- at Velopack.Vpk.Logging.BasicConsole.ExecuteProgressAsync(Func2 action) in ./Velopack.Vpk/Logging/BasicConsole.cs:line 19
at Velopack.Packaging.PackageBuilder1.Run(T options) in ./Velopack.Packaging/PackageBuilder.cs:line 109 at Velopack.Vpk.ProgramCommandExtensions.<>c__DisplayClass3_02.<b__0>d.MoveNext() in ./Velopack.Vpk/Program.cs:line 186

_Originally posted by @SebastianDevelops in https://github.com/velopack/velopack.docs/discussions/8#discussioncomment-9571801_

**Comment by caesay** [comment]
@SebastianDevelops What version of VPK are you using?

**Comment by SebastianDevelops** [comment]
This is according to the logs: '_Velopack CLI 0.0.359, for distributing applications.'_

**Comment by caesay** [comment]
I've been able to pack a valid application using both the latest stable (0.0.359) and latest pre-release (0.0.503-gc69e323), so I'll need some more information on how to reproduce the issue before I can look into it further. 

I'd try cleaning your output / build directories first of all, maybe try re-installing velopack etc.

**Comment by SebastianDevelops** [comment]
This is running from an azure pipeline, it ran it about 6 hours ago and the build + pack was successful.
During the pipline process, velopack installs the latest version. The releases folder contains previous manifest files which is the same folder that I run vpk pack to.
For some reason now, it throws the above exception. This is really bad because it is affecting the main branch.

**Comment by SebastianDevelops** [comment]
> This is running from an azure pipeline, I ran it about 6 hours ago and the build + pack was successful. During the pipline process, velopack installs the latest version. The releases folder contains previous manifest files which is the same folder that I run vpk pack on. For some reason now, it throws the above exception. This is really bad because it is affecting the main branch.

Please see what the path/where/hosting/files looks like:

![image](https://github.com/velopack/velopack/assets/95648511/c124364f-7da7-47cf-bc4c-e3ded9284196)

**Comment by SebastianDevelops** [comment]
Below are some of the logs that outputted the exception:

![image](https://github.com/velopack/velopack/assets/95648511/6529c237-15c2-4148-9265-22c5e582bd6f)

**Comment by SebastianDevelops** [comment]
I got this same error trying to build locally, maybe it has something to do with the manifest files?

![image](https://github.com/velopack/velopack/assets/95648511/eb826c7d-9a43-4d6a-8178-5b58a675494c)

**Comment by caesay** [comment]
The error you're getting is saying that Velopack failed to create the `Setup.exe`. When packing your application, VPK grabs a pre-compiled Setup.exe template from inside the nuget package, then replaces some variables in it to customise it to your application. The error indicates that the template `Setup.exe` does not have a magic string that it expects, so it cannot replace the variables. 

In practice, what this means is that the Setup.exe template being used by VPK is corrupt somehow, or VPK is using Setup.exe template from the wrong location.

I am confident that the Setup.exe found in the vpk nuget package does not have this issue since you (and others) have been using it to create releases successfully.

So it could be something specific to your project (eg. vpk is being run in a location where it is finding a file named 'Setup.exe' which is not the template exe it expects) or it could be something specific to your machine. 

If you can reproduce the issue outside of that project eg. in a demo project, please upload it to github so I can take a look.

**Comment by caesay** [comment]
You could also try updating to a newer pre-release version of vpk (but don't forget to update the Velopack package too).

**Comment by SebastianDevelops** [comment]
@caesay, something was corrupt but I cannot put my finger on it. I downloaded the manifest files from my blob storage and got the exception message. BUT when doing `vpk pack` without the pre existing manifest files from blob storage, the command ran successfully

These were fine all along until I ran `vpk pack` using the azure pipelines. Could the error/corruption be during this process? Keep in mind that the path in the `assets.win.json` became the following:

"D:\\a\\1\\HermesWpf\\Releases\\Hermes-1.0.3-delta.nupkg",
"D:\\a\\1\\HermesWpf\\Releases\\Hermes-1.0.3-full.nupkg",
"D:\\a\\1\\HermesWpf\\Releases\\Hermes-win-Portable.zip",
"D:\\a\\1\\HermesWpf\\Releases\\Hermes-win-Setup.exe"

Not sure if this somehow plays s a role.
Also comparing the delta files between the working package versions and the corrupt ones. I see quite a few binaries missing from what was in blob storage(azure pipelines pack) when using Nuget Package Explorer.

Any ideas on what could be causing this?

**Comment by caesay** [comment]
You shouldn't need to preserve the assets.win.json file, it's created on each `vpk pack` and used by `vpk upload`. I don't know what could be going wrong in your case. If you're able to reproduce it outside of your project in a way I can also do myself I will look into it.

**Comment by SebastianDevelops** [comment]
> You shouldn't need to preserve the assets.win.json file, it's created on each `vpk pack` and used by `vpk upload`. I don't know what could be going wrong in your case. If you're able to reproduce it outside of your project in a way I can also do myself I will look into it.

I will do so and add you as a contributor

**Comment by caesay** [comment]
Any updates to this issue? Have you reproduced the issue in a standalone repo I can look at, or resolved your issue in another way?

**Comment by akbartrinanda** [comment]
me too 
![image](https://github.com/velopack/velopack/assets/20968171/96e67ef0-c722-4998-9346-667429009d76)

**Comment by caesay** [comment]
And what version are you on?

**Comment by akbartrinanda** [comment]
> And what version are you on?

![image](https://github.com/velopack/velopack/assets/20968171/ec6748dc-dbe0-4726-a819-3f1be067b625)

**Comment by caesay** [comment]
Can you try on the latest prerelease and let me know if it's still an issue?

**Comment by akbartrinanda** [comment]
> Can you try on the latest prerelease and let me know if it's still an issue?

yes still error:
![image](https://github.com/velopack/velopack/assets/20968171/05d0d18b-2472-4375-8763-446c65235612)

**Comment by akbartrinanda** [comment]
> Can you try on the latest prerelease and let me know if it's still an issue?

does it have something to do with the number of files? because when I deleted many files from 174 files to 25 files, vpk pack was successful
![image](https://github.com/velopack/velopack/assets/20968171/cb1fa8b4-8e85-4ae4-8518-8140657fcfba)

**Comment by caesay** [comment]
No it doesn't have to do with the number of files. Do you have an `Update.exe` or a `Setup.exe` file in your program output or anywhere in your project?

**Comment by akbartrinanda** [comment]
> No it doesn't have to do with the number of files. Velopack will quite happily process thousands of files. Do you have an `Update.exe` or a `Setup.exe` file in your program output or anywhere in your project? I think there may be a file in your project with a conflicting name causing the issue, and you deleted it therefore fixing the issue.

There is no file with the name `Setup.exe` or `Update.exe`

**Comment by caesay** [comment]
I would obviously love to get to the bottom of this and fix it - but as I still don't have any idea what the cause is, this issue will remain blocked until someone can reproduce it in an isolated app - ideally a github repo I can `git clone` and look at locally.

**Comment by SebastianDevelops** [comment]
I will try my best to create an isolated solution for you @caesay, I just need to find the time.

**Comment by SebastianDevelops** [comment]
I found a **temporary workaround** to this issue @akbartrinanda, until it gets fixed. The following are the steps I follow to avoid this issue.

1. Create binary output files are usual
    `dotnet publish -c Release --self-contained -r win-x64 -o your/specified/path`
   
2. _(optional)_ `cd ` into `your/specified/path`

3. Run `vpk download`, for a full description of how to run this [read the following from the docs](https://docs.velopack.io/distributing/deploy-cli "Velopack documentation").

4. After `vpk download` has ran successfully, a folder called `Releases` is created which **contains the `.nupkg` with latest version of your application**. 

5. Now you are safe to run `vpk pack` as usual without encountering the error described in this issue.

I stand to be corrected on why this works but my hypothesis is that when we run `vpk pack` on a directory that contains all prior versions, _eg. 1.0.0.0-1.0.0.20_, Velopack seems to rebuild all the `.nupkg` files, this rebuild could be making previous/latest files corrupt in the process hence we get the above exception.

**Comment by caesay** [comment]
I'm afraid your hypothesis is not correct.

The default output path for releases is always `.\Releases`. If you run `vpk pack` or `vpk download` without providing the `-o` arg, it will get placed into `.\Releases` as you've noticed. In general, you should be using the same output dir (`-o` ) for every velopack command you run, so that they can correctly share the same output directory. This is crucial because otherwise your `releases.{channel}.json` file will not be valid.

Velopack will read the files in your output dir (for the purposes of re-constructing your `releases.{channel}.json` with the valid entries.

The error you're encountering (`PlaceHolderNotFoundInAppHostException`) occurs specifically when building the `Setup.exe` for your _new_ version. The version of your app that is being packed right now when you call `vpk pack`. It has nothing to do with older versions, however as I mentioned above, if there is a file in your working directory (not your output directory) which looks like it might be `Setup.exe` or `Update.exe`, it's possible that Velopack has tried to take that and customise it. This is why changing the directory you run vpk from may have had an impact... because the trouble-causing file is no longer in the working directory.

Can you show me a list of what files you have in your "directory that contains all prior versions, eg. 1.0.0-1.0.20" as well as the working directory? (ie. the directory you run vpk from)

**Comment by SebastianDevelops** [comment]
> Can you show me a list of what files you have in your "directory that contains all prior versions, eg. 1.0.0-1.0.20" as well as the working directory? (ie. the directory you run vpk from)

This is the directory with all prior versions:
![image](https://github.com/velopack/velopack/assets/95648511/9df25ccb-b6de-4ac2-8d12-0c4152f4013e)

I cannot give you my exact working directory as I run vpk pack from an azure pipeline.

The pipeline environment _working directory_ would contain the following after running `vpk download`:
![image](https://github.com/velopack/velopack/assets/95648511/ceecd9dd-2c3f-4b27-8f54-2ad3ca77905e)

Once running `vpk pack` command, it would look like this, and this will be uploaded to storage and replace the existing `releases.win.json`, `Hermes-win-Setup.exe`, previous full `.nupkg` and `Hermes-win-Portable.zip`:
![image](https://github.com/velopack/velopack/assets/95648511/f0f1c8d2-f21b-4911-ba24-8cdb03c3ecb2)

**Keep in mind** that would I provided above works everytime and never gives the `PlaceHolderNotFoundInAppHostException` error.
My hypothesis might be incorrect but this solution seems to work fine.

**Comment by caesay** [comment]
Any update from either of you in terms of providing repro steps?

**Comment by caesay** [comment]
Happy to re-open this if anyone can reproduce it for me to test
