### ISSUE TITLE
Filenames with spaces cause the deltas to fail, resulting in full being downloaded

### ISSUE THREAD

**Issue by cunnpole** [velopack/velopack#162]
After "Patch applied successfully" I get the following exception;

Unable to apply delta updates, falling back to full update.: System.Exception: Invalid release entry: 903B6727BF05FA7B1F46C78066DAA37FFE72926E Caiman IQ Desktop.deps.json.shasum 117288
   at Velopack.ReleaseEntry.ParseReleaseEntry(String entry)
   at Velopack.Compression.DeltaPackage.verifyPatchedFile(String relativeFilePath, String inputFile, String tempTargetFile)
   at Velopack.Compression.DeltaPackage.applyDiffToFile(String deltaPath, String relativeFilePath, String workingDirectory)
   at Velopack.Compression.DeltaPackage.ApplyDeltaPackageFast(String workingPath, String deltaPackageZip, Action`1 progress)
   at Velopack.UpdateManager.DownloadAndApplyDeltaUpdates(String extractedBasePackage, UpdateInfo updates, Action`1 progress, CancellationToken cancelToken)
   at Velopack.UpdateManager.DownloadUpdatesAsync(UpdateInfo updates, Action`1 progress, Boolean ignoreDeltas, CancellationToken cancelToken)

The issue appears to be that entryRegex format doesnt like that:

https://github.com/velopack/velopack/blob/1e760b40d43f4075532c208bf472e2cda5705b64/src/Velopack/ReleaseEntry.cs#L212

As an example, this fails:
```
Regex entryRegex = new Regex(@"^([0-9a-fA-F]{40})\s+(\S+)\s+(\d+)[\r]*$");
var m = entryRegex.Match("903B6727BF05FA7B1F46C78066DAA37FFE72926E Caiman IQ Desktop.deps.json.shasum 117288");
```

Whereas this passes and on the following group test:
`var m = entryRegex.Match("903B6727BF05FA7B1F46C78066DAA37FFE72926E CaimanIQDesktop.deps.json.shasum 117288");`

I would offer to fix this but this regex isnt compatible with my brain...

**Comment by caesay** [comment]
Thanks for the report. 

Looks like similar to 
- https://github.com/Squirrel/Squirrel.Windows/pull/1401
- https://github.com/Squirrel/Squirrel.Windows/issues/1283

`ReleaseEntry` is a deprecated format in Velopack and it doesn't (and can not) support spaces in file names. 

The solution will be to replace this with a new format.

**Comment by cunnpole** [comment]
For anyone else in the scenario, the simplest option for me was to remove spaces from my filenames and use --packTitle "Something With Spaces" to work around the issue

**Comment by caesay** [comment]
This will get fixed by #63 which is in the works
