### ISSUE TITLE
Mac: Bundled apps can't run process from PATH

### ISSUE THREAD

**Issue by IvanJosipovic** [velopack/velopack#220]
### OS

Mac >=10.15

### Programming Language

dotnet 8

### VPK Version

0.0.594

### Library Version

https://github.com/IvanJosipovic/KubeUI

### What happened?

My app bundled for Mac has issues executing a process which is available in the PATH. This error doesn't occur if I run the app manually without bundling.

Running app with bundling:
![image](https://github.com/user-attachments/assets/82fb1b56-496d-4c1c-82ce-fcf095287b4b)

Running app without bundling:
![image](https://github.com/user-attachments/assets/3639dd05-d11a-4afb-a908-9c97c3851229)

### Relevant log output

```shell
2024-09-08T12:34:43.1980050-07:00	FAIL	[KubeUI.Client.Cluster]	[0]	Error connecting to ij-dev-aks - k8s.Exceptions.KubeConfigException: external exec failed due to: An error occurred trying to start process 'kubelogin' with working directory '/'. No such file or directory
   at k8s.KubernetesClientConfiguration.ExecuteExternalCommand(ExternalExecution config)
   at k8s.KubernetesClientConfiguration.SetUserDetails(K8SConfiguration k8SConfig, Context activeContext)
   at k8s.KubernetesClientConfiguration.InitializeContext(K8SConfiguration k8SConfig, String currentContext)
   at k8s.KubernetesClientConfiguration.GetKubernetesClientConfiguration(String currentContext, String masterUrl, K8SConfiguration k8SConfig)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFileAsync(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(FileInfo kubeconfig, String currentContext, String masterUrl, Boolean useRelativePaths)
   at k8s.KubernetesClientConfiguration.BuildConfigFromConfigFile(String kubeconfigPath, String currentContext, String masterUrl, Boolean useRelativePaths)
   at KubeUI.Client.Cluster._getClientConfiguration()
   at KubeUI.Client.Cluster.Connect()
```

**Comment by IvanJosipovic** [comment]
I was able to resolve this by creating a custom info.plist and setting:
```
    <key>LSEnvironment</key>
    <dict>
        <key>PATH</key>
        <string>/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:</string>
    </dict>
```

**Comment by caesay** [comment]
Would you expect Velopack to add the lines which you've shared to the auto generated plist? Are there any potential issues if we do?

**Comment by IvanJosipovic** [comment]
> Would you expect Velopack to add the lines which you've shared to the auto generated plist? Are there any potential issues if we do?

Hmm, its hard to say, the info.plist should be using the principle of least privilege. I assume, if the user publishes the app to the App Store that the info.plist is scrutinized. 

For my perspective, i think documenting the --plist option in the documentation would be helpful, as I was only able to find that option by looking at the code.
